"""Few-shot example bank (used for RAG retrieval) and a disjoint held-out
eval set (used only to score generations, never shown in any prompt).
Keeping these two sets disjoint matters: if an eval question's own gold
example were retrievable, the "RAG" system would just be doing lookup, not
generation, and the comparison against the baseline would be meaningless.
"""

FEWSHOT_CORPUS = [
    ("List all customers from Bangalore.",
     "SELECT name FROM customers WHERE city = 'Bangalore';"),
    ("Show the names of products in the Electronics category.",
     "SELECT name FROM products WHERE category = 'Electronics';"),
    ("What is the price of the Office Chair?",
     "SELECT price FROM products WHERE name = 'Office Chair';"),
    ("How many orders has each customer placed?",
     "SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id;"),
    ("What is the total quantity ordered for each product?",
     "SELECT product_id, SUM(quantity) FROM orders GROUP BY product_id;"),
    ("List customers who signed up after 2024-03-01.",
     "SELECT name FROM customers WHERE signup_date > '2024-03-01';"),
    ("What are the names of all products cheaper than 1000?",
     "SELECT name FROM products WHERE price < 1000;"),
    ("How many distinct customers have placed an order?",
     "SELECT COUNT(DISTINCT customer_id) FROM orders;"),
    ("List all product names ordered by price descending.",
     "SELECT name FROM products ORDER BY price DESC;"),
    ("Show the order id and quantity for orders placed on 2024-05-04.",
     "SELECT order_id, quantity FROM orders WHERE order_date = '2024-05-04';"),
    ("What is the average price of products in the Furniture category?",
     "SELECT AVG(price) FROM products WHERE category = 'Furniture';"),
    ("List the names of customers who live in Mumbai.",
     "SELECT name FROM customers WHERE city = 'Mumbai';"),
    ("How many products are there in each category?",
     "SELECT category, COUNT(*) FROM products GROUP BY category;"),
    ("What is the most expensive product?",
     "SELECT name FROM products ORDER BY price DESC LIMIT 1;"),
    ("List order ids with quantity greater than 1.",
     "SELECT order_id FROM orders WHERE quantity > 1;"),
    ("Show all customer names and their city.",
     "SELECT name, city FROM customers;"),
    ("What is the total number of orders in the system?",
     "SELECT COUNT(*) FROM orders;"),
    ("List the names of products with a price of exactly 799.",
     "SELECT name FROM products WHERE price = 799;"),
    ("Show customer names who signed up before 2024-02-01.",
     "SELECT name FROM customers WHERE signup_date < '2024-02-01';"),
    ("What is the cheapest product in the Stationery category?",
     "SELECT name FROM products WHERE category = 'Stationery' ORDER BY price ASC LIMIT 1;"),
]

EVAL_SET = [
    ("Which customers are based in Delhi?",
     "SELECT name FROM customers WHERE city = 'Delhi';"),
    ("How many products cost more than 500?",
     "SELECT COUNT(*) FROM products WHERE price > 500;"),
    ("What is the total quantity of items ordered by customer 1?",
     "SELECT SUM(quantity) FROM orders WHERE customer_id = 1;"),
    ("List product names sorted alphabetically.",
     "SELECT name FROM products ORDER BY name ASC;"),
    ("How many orders were placed in May 2024?",
     "SELECT COUNT(*) FROM orders WHERE order_date LIKE '2024-05%';"),
    ("What is the name of customer with id 3?",
     "SELECT name FROM customers WHERE customer_id = 3;"),
    ("List all distinct product categories.",
     "SELECT DISTINCT category FROM products;"),
    ("What is the minimum price among all products?",
     "SELECT MIN(price) FROM products;"),
    ("How many customers are there in total?",
     "SELECT COUNT(*) FROM customers;"),
    ("List order ids for orders of product id 1.",
     "SELECT order_id FROM orders WHERE product_id = 1;"),
]
